name: Python linting

on:
  pull_request:
  push:
    branches:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Lint with Ruff
        uses: chartboost/ruff-action@v1
